// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC02wuGnxEw3RYCrqPqgUQO0giRr2SjS3Y',
    appId: '1:227105226409:web:bac0622681d5989d75b3b8',
    messagingSenderId: '227105226409',
    projectId: 'meditrack-49903',
    authDomain: 'meditrack-49903.firebaseapp.com',
    storageBucket: 'meditrack-49903.firebasestorage.app',
    measurementId: 'G-109CK9K7WG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhD10kLsLHdffUjmiI_GmWp2ZtvHM96WM',
    appId: '1:227105226409:android:a3f97f2e0a80897575b3b8',
    messagingSenderId: '227105226409',
    projectId: 'meditrack-49903',
    storageBucket: 'meditrack-49903.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFOWqpqwUzBiVmooW--B2fI57eLpNbnNM',
    appId: '1:227105226409:ios:a5af2a9d87c82dde75b3b8',
    messagingSenderId: '227105226409',
    projectId: 'meditrack-49903',
    storageBucket: 'meditrack-49903.firebasestorage.app',
    iosBundleId: 'com.example.meditrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFOWqpqwUzBiVmooW--B2fI57eLpNbnNM',
    appId: '1:227105226409:ios:a5af2a9d87c82dde75b3b8',
    messagingSenderId: '227105226409',
    projectId: 'meditrack-49903',
    storageBucket: 'meditrack-49903.firebasestorage.app',
    iosBundleId: 'com.example.meditrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC02wuGnxEw3RYCrqPqgUQO0giRr2SjS3Y',
    appId: '1:227105226409:web:f2e614c167db9f8675b3b8',
    messagingSenderId: '227105226409',
    projectId: 'meditrack-49903',
    authDomain: 'meditrack-49903.firebaseapp.com',
    storageBucket: 'meditrack-49903.firebasestorage.app',
    measurementId: 'G-L0LN8Q8GDR',
  );
}
